### ISSUE TITLE
Would like to add a place where agents can be configured

### ISSUE THREAD

**Issue by bambuo** [dialect-app/dialect#388] opened 2024-05-27 01:46 UTC
This requirement is mainly due to the fact that the user's region may not be able to access Google and most non local networks under normal circumstances, and they do not want to set the proxy as a global scenario. Therefore, a gateway that can configure the proxy service is needed to ensure that the program uses proxy configuration for interface calls during runtime

**Comment by mufeedali** [comment] 2024-11-07 17:49
Duplicate of #115 . We also have some interest in this feature and will look into implementing it :)

**Closed by mufeedali** 2024-11-07 17:49 UTC
