### ISSUE TITLE
Provide offline translations utilizing Mozillas translation mechanism?

### ISSUE THREAD

**Issue by stefan-niedermann** [dialect-app/dialect#277] opened 2022-08-21 07:18 UTC
A complete offline working app has several advantages

- Huge privacy improvements
- Not depending on 3rd party servers which might or might not be availabke
- Network not required (traveling via train or so)
- Saving metered data volume
- ...

Mozilla allows to translate websites completely offline / local within the Firefox browser utilizing the `Bergamot` project. Maybe this can be adapted as an additional option?

https://browser.mt/software

**Comment by fushinari** [comment] 2022-08-21 07:45
Duplicate of #183

**Closed** 2022-08-21 07:45 UTC

**Comment by stefan-niedermann** [comment] 2022-08-21 07:52
Oof, how could i miss that? 🙈 sorry for the noise!

**Comment by fushinari** [comment] 2022-08-21 07:55
No worries. :)
