### ISSUE TITLE
[Feature request] Global shortcut to open the app with selected text

### ISSUE THREAD

**Issue by reuseman** [dialect-app/dialect#219] opened 2021-11-06 10:32 UTC
It would be great to have a global shortcut to let Dialect translate immediately the selected text

**Comment by rafaelmardojai** [comment] 2021-11-06 12:03
Duplicate of #207.

**Comment by reuseman** [comment] 2021-11-09 14:19
Even though it's not possible to have access to the selection in Wayland, it's still possible to have access to the Clipboard. So it could still be useful to copy the content in the clipboard with a Ctrl+C and then using a shortcut to open Dialect with the content already pasted into it and translated

**Comment by rafaelmardojai** [comment] 2021-11-09 14:36
We could add a command line flag to do that, but you will need to manually set the global shortcut until an API is added to `xdg-desktop-portal`.

**Comment by fushinari** [comment] 2021-11-10 17:41
This works:
![Screenshot from 2021-11-10 23-10-06](https://user-images.githubusercontent.com/28823274/141164821-8e128d34-befd-4658-a88d-55763e5a59be.png)

```bash
sh -c 'dialect -t "$(wl-paste -p)"'
```

**Comment by fushinari** [comment] 2021-11-22 07:11
Closing this for now since I've already given a working solution and because there's no other good way to implement it on our side for now. If there's ever a better way to implement it, feel free to reopen or open another issue.

**Closed by fushinari** 2021-11-22 07:11 UTC
