### ISSUE TITLE
Missing fonts japanese and korean

### ISSUE THREAD

**Issue by pemartins1** [dialect-app/dialect#208] opened 2021-09-28 14:39 UTC
At least the japanese and korean fonts are missing in flatpack 1.3.0 version, here's a printscreen for japanese:
![dialect-jap](https://user-images.githubusercontent.com/23001662/135109003-09efbb3b-3c6b-405e-b185-d4672c48c06a.png)

Also tested for arabic and chinese but those are fine.

**Comment by dtantono** [comment] 2021-09-30 01:57
I am curious. which kind of Chinese. Traditional or Simplified?

**Comment by pemartins1** [comment] 2021-09-30 19:39
> I am curious. which kind of Chinese. Traditional or Simplified?

Simplified was ok, but I just tested a longer text and there are also some characteres missing. And for Traditional chinese the font is also broken, just tested it.

**Comment by fushinari** [comment] 2021-12-29 07:40
I can't seem to reproduce this. Can you still reproduce this?

**Comment by Ashdemai** [comment] 2021-12-29 07:41
> I can't seem to reproduce this. Can you still reproduce this?

Go into the program and start typing in japanese, does it not show up as boxes to you?

**Comment by fushinari** [comment] 2021-12-29 07:53
> Go into the program and start typing in japanese, does it not show up as boxes to you?

As part of some work for the next version, I'm using Japanese and Korean exclusively. See https://github.com/dialect-app/dialect/pull/227#issuecomment-1002442726 for an example

**Comment by fushinari** [comment] 2022-04-03 16:43
I think this has already been fixed in the runtimes since I don't encounter this myself and extensively test using Chinese and Japanese text.

**Closed by fushinari** 2022-04-03 16:43 UTC
Labels: bug
