### ISSUE TITLE
Trying to translate text containing ": *" fails

### ISSUE THREAD

**Issue by wjt** [dialect-app/dialect#330] opened 2023-06-07 09:36 UTC
With Dialect 2.1.1 from Flathub, I see the following error for any attempt to translate anything:

![Screenshot from 2023-06-07 10-35-11](https://github.com/dialect-app/dialect/assets/86760/0939b30c-d757-4cbc-af62-9787b0b15298)

In the journal, I see:

```
Jun 07 10:35:33 camille app.drey.Dialect.desktop[13722]: ERROR:root:Translator Error: the JSON object must be str, bytes or bytearray, not NoneType
```

I am using Google Translate.

**Comment by wjt** [comment] 2023-06-07 09:41
Weird. I closed and reopened the app and the issue went away.

**Comment by wjt** [comment] 2023-06-07 09:48
OK, I hit this error again, and tracked down the problematic sequence of characters:

```
: *
```

Once you attempt to translate a block of text containing that three-character string (colon, space, asterisk) then all future attempts to translate fail until I restart the app

**Comment by rafaelmardojai** [comment] 2023-06-12 13:35
It is a bit inconsistent to me, it does not always fail and when it does, the retry is successful.

**Comment by mufeedali** [comment] 2023-06-14 19:42
Strange, I'm not able to reproduce this at all.

**Comment by rafaelmardojai** [comment] 2023-06-14 19:44
> Strange, I'm not able to reproduce this at all.
> 
> I've tried Dialect's current state (main), 2.1.1 from Flathub and also 2.1.1 from Fedora's official RPM repos.

In my case, if I just translate `: *` nothings happens. The issue appears when you use it with text, like `hello: *`.

**Comment by mufeedali** [comment] 2023-06-15 04:18
Unable to reproduce with `hello: *` as well :(

**Comment by rafaelmardojai** [comment] 2023-06-15 04:30
> Unable to reproduce with `hello: *` as well :(

It not always happens on the first try for me. Has I said is quite inconsistent. Usually I have to change the dest lang a few times. It happens with German for example.

**Comment by meybonomme** [comment] 2024-02-22 21:07
> ```
> : *
> ```

The same happens if text contains a character `/`

**Comment by mufeedali** [comment] 2024-04-14 15:05
Can somebody provide any **complete** sample strings where this issue is seen consistently? I'm unable to reproduce this at all from my end

**Comment by rafaelmardojai** [comment] 2024-04-16 15:34
I also can't reproduce this, probably something changed on the Google side. Let's close this for now and reopen if necessary.

**Closed by rafaelmardojai** 2024-04-16 15:34 UTC
Labels: bug, google
